name: Build OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc zlib1g-dev file wget
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget


    - name: Clone OpenWrt source code
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.3
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Update UBNT_VERSION in common-ubnt.mk
      run: |
        cd openwrt
        sed -i 's/UBNT_VERSION := 8.5.3/UBNT_VERSION := 8.7.4/g' target/linux/ath79/image/common-ubnt.mk
      
    - name: Copy custom .config
      run: |
        rm -f openwrt/.config
        cp .config openwrt/.config
        
    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-nanostation-ac-loco-firmware
        path: openwrt/bin/targets/
